version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  worker:
    build: ./
    entrypoint: celery
    command: -A ${APP_MAIN} worker --beat -l info -E
    user: nobody
    volumes:
      - ./${APP_DIR}:/data
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      PYTHONPATH: /data
    depends_on:
      - redis
  flower:
    build: ./
    command: celery -A ${APP_MAIN} flower
    volumes:
      - ./${APP_DIR}:/data
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - worker
      - redis